name: Code Quality Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Check export patterns
        run: |
          npx ts-node -e "
            const fs = require('fs');
            const path = require('path');
            const components = process.argv[1];
            const files = fs.readdirSync(components);
            files.forEach(file => {
              if (file.endsWith('.tsx')) {
                const content = fs.readFileSync(path.join(components, file), 'utf8');
                if (!content.includes('export function')) {
                  throw new Error(`${file} does not use export function pattern`);
                }
              }
            });
          " -- components/

      - name: Run ESLint
        run: npx eslint . --ext .ts,.tsx

      - name: Run Prettier
        run: npm run format

      - name: Check formatting
        run: npm run format:check

      - name: Check naming conventions
        run: |
          npx ts-node -e "
            const fs = require('fs');
            const path = require('path');
            function isCamelCase(str) {
              return /^[a-z][a-zA-Z0-9]*$/.test(str);
            }
            // Add your camelCase checking logic here
          "
